spring:
  h2:
    console.enabled: true
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        jdbc:
#          lob:
#            non_contextual_creation: true
#      datasource:
  jpa:
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

logging:
  level:
#    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    com.kasemodel: DEBUG

award:
  initial-data:
    file: dev-data.csv
