spring:
  h2:
    console.enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.kasemodel: DEBUG
    org.hibernate.sql: TRACE
    org.hibernate.type.descriptor.sql: TRACE

award:
  initial-data:
    file: data.csv
